using System;
using System.Collections.Generic;

namespace DataAccess.EFCore.Repository
{
    public partial class vw_sales_invoice
    {
        public string id { get; set; }
        public string created_by { get; set; }
        public DateTime? created_on { get; set; }
        public string modified_by { get; set; }
        public DateTime? modified_on { get; set; }
        public bool? is_active { get; set; }
        public bool? is_locked { get; set; }
        public bool? is_default { get; set; }
        public string owner_id { get; set; }
        public string organization_id { get; set; }
        public string entity_id { get; set; }
        public string despatch_order_id { get; set; }
        public decimal? quantity { get; set; }
        public string uom_id { get; set; }
        public decimal? unit_price { get; set; }
        public decimal? downpayment { get; set; }
        public string lc_date_issue { get; set; }
        public string lc_number { get; set; }
        public string lc_status { get; set; }
        public string lc_issuing_bank { get; set; }
        public decimal? amount { get; set; }
        public decimal? final_price { get; set; }
        public decimal? final_amount { get; set; }
        public string currency_id { get; set; }
        public DateTime? invoice_date { get; set; }
        public string invoice_number { get; set; }
        public string accounting_period_id { get; set; }
        public string sales_type_id { get; set; }
        public string customer_id { get; set; }
        public string bank_account_id { get; set; }
        public string account_number { get; set; }
        public string account_holder { get; set; }
        public string branch_information { get; set; }
        public string swift_code { get; set; }
        public string bank_id { get; set; }
        public string bank_name { get; set; }
        public string bank_code { get; set; }
        public string despatch_order_number { get; set; }
        public string sales_order_id { get; set; }
        public string sales_order_number { get; set; }
        public string product_id { get; set; }
        public string discharge_port { get; set; }
        public string loading_port { get; set; }
        public string product_name { get; set; }
        public string uom_name { get; set; }
        public string uom_symbol { get; set; }
        public string currency_name { get; set; }
        public string currency_code { get; set; }
        public string currency_symbol { get; set; }
        public string accounting_period_name { get; set; }
        public string organization_name { get; set; }
        public string business_unit_id { get; set; }
        public string business_unit_name { get; set; }
        public string record_created_by { get; set; }
        public string record_modified_by { get; set; }
        public string record_owning_user { get; set; }
        public string record_owning_team { get; set; }
        public string sales_type_name { get; set; }
        public string invoice_type_id { get; set; }
        public string invoice_type_name { get; set; }
        public string customer_name { get; set; }
        public string seller_name { get; set; }
        public string seller_id { get; set; }
        public string bill_to_name { get; set; }
        public string bill_to { get; set; }
        public string contract_product_name { get; set; }
        public string contract_product_id { get; set; }
        public string analyte_name { get; set; }
        public string analyte_standard_name { get; set; }
        public decimal? sips_value { get; set; }
        public decimal? sips_target { get; set; }
        public string sales_contract_name { get; set; }
        public string sales_contract_id { get; set; }
        public string sales_contract_term_name { get; set; }
        public string sales_contract_term_id { get; set; }
        public string notes { get; set; }
        public int? adjustment { get; set; }
        public int? ash_price_adj { get; set; }
        public int? ts_price_adj { get; set; }
        public int? cv_price_adj { get; set; }
        public decimal? total_price { get; set; }
        public string quotation_type_id { get; set; }
        public bool? credit_limit_activation { get; set; }
        public decimal? credit_limit { get; set; }
        public string currency_exchange_id { get; set; }
        public string source_currency_id { get; set; }
        public string source_currency_name { get; set; }
        public string source_currency_code { get; set; }
        public string target_currency_id { get; set; }
        public string target_currency_name { get; set; }
        public string target_currency_code { get; set; }
        public string source_currency_symbol { get; set; }
        public string target_currency_symbol { get; set; }
        public decimal? exchange_rate { get; set; }
        public decimal? freight_cost { get; set; }
        public string transaction_code { get; set; }
        public string print_status { get; set; }
        public string correspondent_bank_id { get; set; }
        public string correspondent_account_number { get; set; }
        public string correspondent_account_holder { get; set; }
        public string correspondent_branch_information { get; set; }
        public string correspondent_swift_code { get; set; }
        public string correspondent_bank_name { get; set; }
        public string description_of_goods { get; set; }
        public string consignee { get; set; }
        public DateTime? bl_date { get; set; }
        public DateTime? coa_date { get; set; }
        public DateTime? submit_date { get; set; }
        public DateTime? payment_date { get; set; }
        public decimal? alias5 { get; set; }
        public decimal? alias6 { get; set; }
        public decimal? alias7 { get; set; }
        public decimal? alias8 { get; set; }
        public decimal? alias9 { get; set; }
        public string alias10 { get; set; }
        public string alias11 { get; set; }
        public string alias12 { get; set; }
        public string alias13 { get; set; }
        public string alias14 { get; set; }
        public string alias15 { get; set; }
        public string alias16 { get; set; }
        public string alias17 { get; set; }
        public string alias18 { get; set; }
        public DateTime? alias19 { get; set; }
        public string alias20 { get; set; }
        public string alias21 { get; set; }
        public decimal? insurance_cost { get; set; }
        public decimal? subtotal { get; set; }
        public string response_code { get; set; }
        public string approve_status { get; set; }
        public string approve_by_id { get; set; }
        public string approve_by { get; set; }
        public string disapprove_by_id { get; set; }
        public string disapprove_by { get; set; }
        public string comment { get; set; }
        public string inco_term { get; set; }
        public string szfreightinvoiceno { get; set; }
        public decimal? decfreightpriceton { get; set; }
        public decimal? decfreightamount { get; set; }
        public DateTime? dtmfreightinvoicedatereceive { get; set; }
        public string szfreightcontractno { get; set; }
        public string hba_type { get; set; }
        public decimal? hba_value { get; set; }
        public string formula { get; set; }
        public decimal? hpb { get; set; }
        public decimal? hpb_value { get; set; }
        public bool? is_fobprice { get; set; }
        public decimal? total_price_hpb { get; set; }
        public decimal? fob_price { get; set; }
        public decimal? gcv_arb { get; set; }
        public decimal? gcv_adb { get; set; }
        public decimal? ts_arb { get; set; }
        public decimal? ts_adb { get; set; }
        public decimal? ash_arb { get; set; }
        public decimal? ash_adb { get; set; }
        public decimal? tm_arb { get; set; }
        public decimal? im_adb { get; set; }
        public string loading_port_id { get; set; }
        public DateTime? alias3 { get; set; }
        public string sales_type { get; set; }
    }
}
